import { Feather, Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import React, { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AddressPickerModal } from '../../../src/components/customer/AddressPickerModal';
import { useAuth } from '../../../src/context/AuthContext';
import { useProduct } from '../../../src/context/ProductContext';
import { createRecurringDelivery } from '../../../src/services/recurring.service';
import { RecurringFrequency } from '../../../src/types/recurring.types';
import { addressStorage, SavedAddress } from '../../../src/utils/addressStorage';
import { COLORS } from '../../../src/utils/constants';

const WEEKDAYS = [{ label: 'Mon', value: 1 }, { label: 'Tue', value: 2 }, { label: 'Wed', value: 3 }, { label: 'Thu', value: 4 }, { label: 'Fri', value: 5 }, { label: 'Sat', value: 6 }, { label: 'Sun', value: 0 }];
const FREQUENCIES: { value: RecurringFrequency; label: string; note: string }[] = [{ value: 'daily', label: 'Daily', note: 'Every day' }, { value: '2_per_week', label: '2 per week', note: 'Choose 2 weekdays' }, { value: '3_per_week', label: '3 per week', note: 'Choose 3 weekdays' }];
const BILLING = [{ value: 'per_order', label: 'Per order', note: 'A bill for each delivery' }, { value: 'weekly', label: 'Weekly', note: 'Monday–Sunday' }, { value: 'monthly', label: 'Monthly', note: 'Calendar month' }] as const;
const PAYMENT_METHODS = [{ value: 'cash', labelKey: 'cashOnDelivery' }, { value: 'shop', labelKey: 'payAtShop' }] as const;

export default function RecurringDeliverySetupScreen() {
  const { t } = useTranslation();
  const router = useRouter(); const { instruction } = useLocalSearchParams<{ instruction?: string }>(); const insets = useSafeAreaInsets(); const { user } = useAuth(); const { products, loading: loadingProducts } = useProduct();
  const [productId, setProductId] = useState<string | null>(null); const [quantity, setQuantity] = useState(1); const [frequency, setFrequency] = useState<RecurringFrequency>('daily'); const [deliveryDays, setDeliveryDays] = useState<number[]>([]);
  const [billingFrequency, setBillingFrequency] = useState<'per_order' | 'weekly' | 'monthly'>('weekly'); const [paymentMethod, setPaymentMethod] = useState<'cash' | 'shop' | null>(null); const [addresses, setAddresses] = useState<SavedAddress[]>([]); const [selectedAddressId, setSelectedAddressId] = useState<string | null>(null); const [showAddressPicker, setShowAddressPicker] = useState(false); const [specialInstructions, setSpecialInstructions] = useState(instruction || ''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (instruction) setSpecialInstructions(instruction); }, [instruction]);
  useEffect(() => { if (!productId && products[0]) setProductId(products[0].id); }, [products, productId]);
  const loadAddresses = useCallback(async () => { const all = await addressStorage.getAllAddresses(user); setAddresses(all); setSelectedAddressId((current) => current || all[0]?.id || null); }, [user]);
  useEffect(() => { loadAddresses(); }, [loadAddresses]); useFocusEffect(useCallback(() => { loadAddresses(); }, [loadAddresses]));
  const product = products.find((item) => item.id === productId); const address = addresses.find((item) => item.id === selectedAddressId); const requiredDays = frequency === '2_per_week' ? 2 : frequency === '3_per_week' ? 3 : 0;
  const toggleDay = (day: number) => setDeliveryDays((current) => current.includes(day) ? current.filter((value) => value !== day) : current.length < requiredDays ? [...current, day] : current);
  const weekdayLabel = [...deliveryDays].sort((a, b) => WEEKDAYS.findIndex((d) => d.value === a) - WEEKDAYS.findIndex((d) => d.value === b)).map((day) => WEEKDAYS.find((item) => item.value === day)?.label).join(', ');
  const handleCreate = async () => { if (!product) return Alert.alert(t('selectProduct'), t('chooseOneProduct')); if (!address) return Alert.alert(t('selectAddress'), t('chooseAddress')); if (!paymentMethod) return Alert.alert(t('selectPaymentMethod'), t('selectRecurringPaymentMethod')); if (deliveryDays.length !== requiredDays) return Alert.alert(t('chooseDeliveryDaysTitle'), t('selectRequiredDays', { days: requiredDays })); setSaving(true); try { const response = await createRecurringDelivery({ productId: product.id, productName: product.name, quantity, frequency, deliveryDays: requiredDays ? deliveryDays : undefined, billingFrequency, paymentMethod, deliveryAddress: address.fullAddress || address.address, deliveryAddressId: address.id, specialInstructions: specialInstructions.trim() || undefined }); if (!response.recurringBill?._id) throw new Error('The recurring plan was created, but no bill was returned for confirmation.'); router.replace({ pathname: '/(customer)/recurring-deliveries/bill', params: { billId: response.recurringBill._id, deliveryId: response.recurringDelivery._id || response.recurringDelivery.id } }); } catch (error: any) { Alert.alert(t('Error'), error.message || t('recurringSetupFailed')); } finally { setSaving(false); } };
  return <View style={styles.container}><View style={[styles.header, { paddingTop: insets.top }]}><TouchableOpacity onPress={() => router.back()} style={styles.backButton}><Feather name="arrow-left" size={24} color={COLORS.text} /></TouchableOpacity><Text style={styles.headerTitle}>Set Up Recurring Delivery</Text></View><ScrollView style={styles.content} contentContainerStyle={styles.contentContainer}>
    <View style={styles.card}><Text style={styles.sectionTitle}>1. Select Product</Text><Text style={styles.helperText}>One product per recurring plan. Set the quantity for each delivery.</Text>{loadingProducts ? <ActivityIndicator color={COLORS.primary} /> : products.map((item) => <TouchableOpacity key={item.id} style={[styles.productCard, productId === item.id && styles.selected]} onPress={() => setProductId(item.id)}><View><Text style={styles.productName}>{item.name}</Text><Text style={styles.productMeta}>{item.volume ? `${item.volume} · ` : ''}₹{item.price}</Text></View>{productId === item.id ? <View style={styles.quantity}><TouchableOpacity onPress={() => setQuantity((value) => Math.max(1, value - 1))}><Text style={styles.quantityButton}>−</Text></TouchableOpacity><Text style={styles.quantityValue}>{quantity}</Text><TouchableOpacity onPress={() => setQuantity((value) => value + 1)}><Text style={styles.quantityButton}>+</Text></TouchableOpacity></View> : null}</TouchableOpacity>)}</View>
    <View style={styles.card}><Text style={styles.sectionTitle}>2. Delivery Frequency</Text><View style={styles.grid}>{FREQUENCIES.map((option) => <TouchableOpacity key={option.value} style={[styles.option, frequency === option.value && styles.selected]} onPress={() => { setFrequency(option.value); setDeliveryDays([]); }}><Text style={styles.optionLabel}>{option.label}</Text><Text style={styles.optionNote}>{option.note}</Text></TouchableOpacity>)}</View>{requiredDays > 0 && <><Text style={styles.label}>Select exactly {requiredDays} weekdays ({deliveryDays.length}/{requiredDays})</Text><View style={styles.weekdays}>{WEEKDAYS.map((day) => <TouchableOpacity key={day.value} disabled={!deliveryDays.includes(day.value) && deliveryDays.length >= requiredDays} style={[styles.day, deliveryDays.includes(day.value) && styles.daySelected]} onPress={() => toggleDay(day.value)}><Text style={[styles.dayText, deliveryDays.includes(day.value) && styles.dayTextSelected]}>{day.label}</Text></TouchableOpacity>)}</View></>}</View>
    <View style={styles.card}><Text style={styles.sectionTitle}>3. Delivery Location</Text><TouchableOpacity style={styles.addressButton} onPress={() => setShowAddressPicker(true)}><Ionicons name="location-outline" size={20} color={COLORS.primary} /><Text style={styles.addressText}>{address?.fullAddress || address?.address || 'Select delivery address'}</Text><Feather name="chevron-right" size={20} color={COLORS.textLight} /></TouchableOpacity><Text style={styles.label}>Special instructions (optional)</Text><TextInput style={styles.input} value={specialInstructions} onChangeText={setSpecialInstructions} multiline placeholder="e.g. Leave at door" placeholderTextColor={COLORS.textLight} /></View>
    <View style={styles.card}><Text style={styles.sectionTitle}>4. Billing Frequency</Text><View style={styles.grid}>{BILLING.map((option) => <TouchableOpacity key={option.value} style={[styles.option, billingFrequency === option.value && styles.selected]} onPress={() => setBillingFrequency(option.value)}><Text style={styles.optionLabel}>{option.label}</Text><Text style={styles.optionNote}>{option.note}</Text></TouchableOpacity>)}</View><Text style={styles.label}>{t('selectPaymentMethod')}</Text><View style={styles.grid}>{PAYMENT_METHODS.map((option) => <TouchableOpacity key={option.value} accessibilityRole="radio" accessibilityState={{ selected: paymentMethod === option.value }} style={[styles.option, paymentMethod === option.value && styles.selected]} onPress={() => setPaymentMethod(option.value)}><Text style={styles.optionLabel}>{t(option.labelKey)}</Text></TouchableOpacity>)}</View></View>
    <View style={styles.card}><Text style={styles.sectionTitle}>5. Plan Summary</Text><Text style={styles.summary}>Product: {product ? `${quantity} × ${product.name}` : 'Not selected'}</Text><Text style={styles.summary}>Delivery: {frequency === 'daily' ? 'Daily' : `${frequency === '2_per_week' ? '2' : '3'} days/week — ${weekdayLabel || 'Select weekdays'}`}</Text><Text style={styles.summary}>Billing: {BILLING.find((item) => item.value === billingFrequency)?.label}</Text><Text style={styles.summary}>{t('paymentMethod')}: {paymentMethod ? t(PAYMENT_METHODS.find((item) => item.value === paymentMethod)!.labelKey) : t('notSelected')}</Text><Text style={styles.helperText}>{t('recurringBillScheduleHint')}</Text></View>
    <TouchableOpacity style={[styles.saveButton, saving && styles.disabled]} onPress={handleCreate} disabled={saving || !paymentMethod}>{saving ? <ActivityIndicator color="white" /> : <Text style={styles.saveButtonText}>{t('setUpPlan')}</Text>}</TouchableOpacity>
  </ScrollView><AddressPickerModal visible={showAddressPicker} addresses={addresses} selectedId={selectedAddressId} onClose={() => setShowAddressPicker(false)} onSelect={async (item) => { setSelectedAddressId(item.id); await addressStorage.setSelectedAddressId(item.id); }} onAddNew={() => { setShowAddressPicker(false); router.push('/(customer)/address/search'); }} /></View>;
}
const styles = StyleSheet.create({ container:{flex:1,backgroundColor:COLORS.accent},header:{flexDirection:'row',alignItems:'center',justifyContent:'center',paddingHorizontal:20,paddingBottom:16,borderBottomWidth:1,borderBottomColor:'#E2E8F0'},backButton:{position:'absolute',left:20,bottom:12},headerTitle:{fontSize:16,fontWeight:'600',color:COLORS.text},content:{flex:1},contentContainer:{padding:16,paddingBottom:32},card:{backgroundColor:COLORS.secondary,borderRadius:16,padding:16,marginBottom:14},sectionTitle:{fontSize:16,fontWeight:'700',color:COLORS.text,marginBottom:8},helperText:{fontSize:13,color:COLORS.textLight,lineHeight:18,marginBottom:12},productCard:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'#E2E8F0',borderRadius:12,padding:12,marginTop:8},selected:{borderColor:COLORS.primary,backgroundColor:'#EFF6FF'},productName:{fontSize:15,fontWeight:'600',color:COLORS.text},productMeta:{fontSize:13,color:COLORS.textLight,marginTop:3},quantity:{flexDirection:'row',alignItems:'center',gap:14},quantityButton:{fontSize:24,color:COLORS.primary,fontWeight:'600',paddingHorizontal:4},quantityValue:{fontSize:16,fontWeight:'700',color:COLORS.text},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},option:{flexGrow:1,minWidth:'30%',borderWidth:1,borderColor:'#E2E8F0',borderRadius:10,padding:10},optionLabel:{fontSize:14,fontWeight:'600',color:COLORS.text},optionNote:{fontSize:11,color:COLORS.textLight,marginTop:3},label:{fontSize:13,fontWeight:'600',color:COLORS.text,marginTop:14,marginBottom:8},weekdays:{flexDirection:'row',gap:6},day:{flex:1,alignItems:'center',paddingVertical:9,borderRadius:8,borderWidth:1,borderColor:'#E2E8F0'},daySelected:{backgroundColor:COLORS.primary,borderColor:COLORS.primary},dayText:{fontSize:12,fontWeight:'600',color:COLORS.text},dayTextSelected:{color:'white'},addressButton:{flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:'#E2E8F0',borderRadius:10,padding:12},addressText:{flex:1,fontSize:14,color:COLORS.text},input:{borderWidth:1,borderColor:'#E2E8F0',borderRadius:10,padding:12,minHeight:70,textAlignVertical:'top',color:COLORS.text},summary:{fontSize:14,color:COLORS.text,marginBottom:7},saveButton:{backgroundColor:COLORS.primary,borderRadius:12,alignItems:'center',padding:15},saveButtonText:{color:'white',fontSize:16,fontWeight:'700'},disabled:{opacity:.65} });
