import { Feather } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { confirmRecurringBill, getRecurringBill, RecurringBill } from '../../../src/services/recurring.service';
import { COLORS } from '../../../src/utils/constants';

const date = (value?: string) => value ? new Date(value).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }) : 'Not available';
const period = (bill: RecurringBill) => `${new Date(bill.periodStart).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} – ${new Date(bill.periodEnd).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}`;
export default function RecurringBillScreen() {
  const { t } = useTranslation();
  const { billId } = useLocalSearchParams<{ billId: string }>(); const router = useRouter(); const insets = useSafeAreaInsets(); const [bill, setBill] = useState<RecurringBill | null>(null); const [loading, setLoading] = useState(true); const [confirming, setConfirming] = useState(false);
  const load = useCallback(async () => { if (!billId) return; try { const response = await getRecurringBill(billId); setBill(response.recurringBill); } catch (error: any) { Alert.alert(t('unableToLoadBill'), error.message || t('pleaseTryAgain')); } finally { setLoading(false); } }, [billId, t]); useEffect(() => { load(); }, [load]);
  const confirm = async () => { if (!bill) return; setConfirming(true); try { await confirmRecurringBill(bill._id); await load(); } catch (error: any) { Alert.alert(t('confirmationFailed'), error.message || t('pleaseTryAgain')); } finally { setConfirming(false); } };
  if (loading || !bill) return <View style={styles.center}><ActivityIndicator color={COLORS.primary} /></View>;
  const confirmed = bill.status === 'confirmed'; const next = bill.scheduledDeliveryDates?.[0]; const plan = typeof bill.recurringDeliveryId === 'string' ? undefined : bill.recurringDeliveryId; const weekdays = plan?.deliveryDays?.map((day) => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][day]).join(', ');
  return <View style={styles.container}><View style={[styles.header, { paddingTop: insets.top }]}><TouchableOpacity onPress={() => router.back()}><Feather name="arrow-left" size={24} color={COLORS.text} /></TouchableOpacity><Text style={styles.title}>{confirmed ? t('recurringDeliveryConfirmed') : t('reviewRecurringBill')}</Text><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={styles.content}>
    {confirmed && <View style={styles.success}><Feather name="check-circle" size={28} color="#059669" /><Text style={styles.successTitle}>{t('billConfirmedSuccess')}</Text><Text style={styles.successText}>{t('offlinePaymentNote')}</Text></View>}
    <View style={styles.card}><Row label={t('Product')} value={bill.productName} /><Row label={t('quantity')} value={`${bill.quantityPerDelivery}`} /><Row label="Delivery" value={plan?.frequency === 'daily' ? 'Daily' : plan?.frequency === '2_per_week' ? `2 days/week${weekdays ? ` — ${weekdays}` : ''}` : plan?.frequency === '3_per_week' ? `3 days/week${weekdays ? ` — ${weekdays}` : ''}` : 'Saved recurring schedule'} /><Row label="Billing" value={bill.billingFrequency === 'per_order' ? 'Per order' : bill.billingFrequency[0].toUpperCase() + bill.billingFrequency.slice(1)} /><Row label="Billing period" value={period(bill)} /><Row label="Amount due" value={`₹${bill.amount}`} strong /><Row label="Due date" value={date(bill.dueDate)} /><Row label={t('paymentMethod')} value={(bill.paymentMethod || bill.preferredPaymentMethod) === 'shop' ? t('payAtShop') : (bill.paymentMethod || bill.preferredPaymentMethod) === 'cash' ? t('cashOnDelivery') : t('paymentMethodNotRecorded')} /><Row label={t('status')} value={bill.status[0].toUpperCase() + bill.status.slice(1)} /><Row label="Next delivery" value={date(next)} /></View>
    {bill.status === 'pending' ? <TouchableOpacity style={styles.button} disabled={confirming} onPress={confirm}>{confirming ? <ActivityIndicator color="white" /> : <Text style={styles.buttonText}>{t('confirmBill')}</Text>}</TouchableOpacity> : <TouchableOpacity style={styles.outline} onPress={() => router.replace('/(customer)/recurring-deliveries')}><Text style={styles.outlineText}>{t('viewRecurringDeliveries')}</Text></TouchableOpacity>}
  </ScrollView></View>;
}
function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={[styles.value, strong && styles.strong]}>{value}</Text></View>; }
const styles = StyleSheet.create({container:{flex:1,backgroundColor:COLORS.accent},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:16,borderBottomWidth:1,borderBottomColor:'#E2E8F0'},title:{fontSize:16,fontWeight:'700',color:COLORS.text},content:{padding:16},success:{backgroundColor:'#ECFDF5',borderWidth:1,borderColor:'#A7F3D0',borderRadius:14,padding:16,alignItems:'center',marginBottom:14},successTitle:{fontSize:17,fontWeight:'700',color:'#065F46',marginTop:6},successText:{fontSize:13,color:'#047857',marginTop:4},card:{backgroundColor:'white',borderRadius:16,padding:16},row:{paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#F1F5F9'},label:{fontSize:12,color:COLORS.textLight,marginBottom:3},value:{fontSize:15,color:COLORS.text,fontWeight:'600'},strong:{fontSize:20,color:COLORS.primary},button:{backgroundColor:COLORS.primary,borderRadius:12,alignItems:'center',padding:15,marginTop:16},buttonText:{color:'white',fontWeight:'700',fontSize:16},outline:{borderColor:COLORS.primary,borderWidth:1,borderRadius:12,alignItems:'center',padding:15,marginTop:16},outlineText:{color:COLORS.primary,fontWeight:'700'}});
